# Enable mouse emulation.
# CONFIG_ZMK_POINTING=y

# Change idle settings
# CONFIG_ZMK_IDLE_TIMEOUT=30000

# Deep sleep settings
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Custom keyboard name (max. 16 characters)
# CONFIG_ZMK_KEYBOARD_NAME="My Keyboard"

# Intel/Realtek BT-Chip Fix für Windows
CONFIG_BT_CTLR_PHY_2M=n

# BT-Sendeleistung erhöhen
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Windows-spezifische Fixes
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
